-- BORRADO INICIAL
DROP TABLE IF EXISTS SUMINISTRA CASCADE;
DROP TABLE IF EXISTS ASISTE_A CASCADE;
DROP TABLE IF EXISTS COMPATIBILIDAD CASCADE;
DROP TABLE IF EXISTS TRABAJA_EN CASCADE;
DROP TABLE IF EXISTS FASE CASCADE;
DROP TABLE IF EXISTS PROYECTO CASCADE;
DROP TABLE IF EXISTS VEHICULO CASCADE;
DROP TABLE IF EXISTS EMPLEADO CASCADE;
DROP TABLE IF EXISTS CLIENTE CASCADE;
DROP TABLE IF EXISTS PERSONA CASCADE;
DROP TABLE IF EXISTS RODAJE CASCADE;
DROP TABLE IF EXISTS MODELO_CATALOGO CASCADE;
DROP TABLE IF EXISTS PROVEEDOR CASCADE;
DROP TABLE IF EXISTS PIEZA CASCADE;

-- 1. TABLAS INDEPENDIENTES (MAESTRAS)

CREATE TABLE PERSONA (
    DNI VARCHAR(20) PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Apellidos VARCHAR(100) NOT NULL,
    Email VARCHAR(100),
    Telefono VARCHAR(20)
);

CREATE TABLE MODELO_CATALOGO (
    ID_Modelo SERIAL PRIMARY KEY,
    Nombre_Comercial VARCHAR(100) NOT NULL -- Ej: 'Series IIA 88', 'Defender 110'
);

CREATE TABLE PIEZA (
    Ref_Pieza VARCHAR(50) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion TEXT,
    Stock_Actual INT DEFAULT 0
);

CREATE TABLE PROVEEDOR (
    CIF VARCHAR(20) PRIMARY KEY,
    Nombre_Empresa VARCHAR(100) NOT NULL,
    Web VARCHAR(100)
);

CREATE TABLE RODAJE (
    ID_Rodaje SERIAL PRIMARY KEY,
    Productora VARCHAR(100) NOT NULL,
    Lugar VARCHAR(100)
);

-- 2. JERARQUÍA (HIJAS DE PERSONA)

CREATE TABLE CLIENTE (
    DNI_Cliente VARCHAR(20) PRIMARY KEY,
    Num_Cuenta VARCHAR(30),
    Fecha_Alta DATE DEFAULT CURRENT_DATE,
    CONSTRAINT FK_Cliente_Persona FOREIGN KEY (DNI_Cliente) REFERENCES PERSONA(DNI)
);

CREATE TABLE EMPLEADO (
    DNI_Empleado VARCHAR(20) PRIMARY KEY,
    NSS VARCHAR(30) UNIQUE NOT NULL, -- Num Seguridad Social
    Salario DECIMAL(10, 2),
    Fecha_Contratacion DATE,
    CONSTRAINT FK_Empleado_Persona FOREIGN KEY (DNI_Empleado) REFERENCES PERSONA(DNI)
);

-- 3. VEHÍCULOS Y PROYECTOS

CREATE TABLE VEHICULO (
    VIN VARCHAR(50) PRIMARY KEY, -- Bastidor
    Matricula VARCHAR(20) UNIQUE NOT NULL,
    Anio INT,
    Color_Original VARCHAR(30),
    Tipo_Motor VARCHAR(50),
    DNI_Propietario VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Vehiculo_Cliente FOREIGN KEY (DNI_Propietario) REFERENCES CLIENTE(DNI_Cliente)
);

CREATE TABLE PROYECTO (
    ID_Proyecto SERIAL PRIMARY KEY,
    Nombre_Descriptivo VARCHAR(150),
    Fecha_Inicio DATE NOT NULL,
    Fecha_Fin DATE,
    VIN_Vehiculo VARCHAR(50) NOT NULL,
    DNI_Supervisor VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Proyecto_Vehiculo FOREIGN KEY (VIN_Vehiculo) REFERENCES VEHICULO(VIN),
    CONSTRAINT FK_Proyecto_Supervisor FOREIGN KEY (DNI_Supervisor) REFERENCES EMPLEADO(DNI_Empleado)
);

-- 4. ENTIDAD DÉBIL (FASE)

CREATE TABLE FASE (
    ID_Proyecto INT,
    Num_Fase INT,
    Nombre_Fase VARCHAR(100) NOT NULL,
    Estado VARCHAR(20) CHECK (Estado IN ('Pendiente', 'En Proceso', 'Terminado')),
    PRIMARY KEY (ID_Proyecto, Num_Fase),
    CONSTRAINT FK_Fase_Proyecto FOREIGN KEY (ID_Proyecto) 
        REFERENCES PROYECTO(ID_Proyecto) 
        ON DELETE CASCADE -- Si borras el proyecto, mueren las fases
);

-- 5. TABLAS INTERMEDIAS (M:N)

CREATE TABLE COMPATIBILIDAD (
    Ref_Pieza VARCHAR(50),
    ID_Modelo INT,
    PRIMARY KEY (Ref_Pieza, ID_Modelo),
    CONSTRAINT FK_Comp_Pieza FOREIGN KEY (Ref_Pieza) REFERENCES PIEZA(Ref_Pieza),
    CONSTRAINT FK_Comp_Modelo FOREIGN KEY (ID_Modelo) REFERENCES MODELO_CATALOGO(ID_Modelo)
);

CREATE TABLE TRABAJA_EN (
    DNI_Empleado VARCHAR(20),
    ID_Proyecto INT,
    Horas_Dedicadas INT DEFAULT 0,
    PRIMARY KEY (DNI_Empleado, ID_Proyecto),
    CONSTRAINT FK_Trabaja_Empleado FOREIGN KEY (DNI_Empleado) REFERENCES EMPLEADO(DNI_Empleado),
    CONSTRAINT FK_Trabaja_Proyecto FOREIGN KEY (ID_Proyecto) REFERENCES PROYECTO(ID_Proyecto)
);

CREATE TABLE ASISTE_A (
    VIN VARCHAR(50),
    ID_Rodaje INT,
    Fecha_Inicio DATE,
    Fecha_Fin DATE,
    Coste_Alquiler DECIMAL(10, 2),
    PRIMARY KEY (VIN, ID_Rodaje),
    CONSTRAINT FK_Asiste_Vehiculo FOREIGN KEY (VIN) REFERENCES VEHICULO(VIN),
    CONSTRAINT FK_Asiste_Rodaje FOREIGN KEY (ID_Rodaje) REFERENCES RODAJE(ID_Rodaje)
);

-- 6. RELACIÓN TERNARIA

CREATE TABLE SUMINISTRA (
    CIF_Proveedor VARCHAR(20),
    Ref_Pieza VARCHAR(50),
    ID_Proyecto INT,
    Precio_Compra DECIMAL(10, 2),
    Fecha_Suministro DATE,
    Cantidad INT,
    PRIMARY KEY (CIF_Proveedor, Ref_Pieza, ID_Proyecto),
    CONSTRAINT FK_Sum_Proveedor FOREIGN KEY (CIF_Proveedor) REFERENCES PROVEEDOR(CIF),
    CONSTRAINT FK_Sum_Pieza FOREIGN KEY (Ref_Pieza) REFERENCES PIEZA(Ref_Pieza),
    CONSTRAINT FK_Sum_Proyecto FOREIGN KEY (ID_Proyecto) REFERENCES PROYECTO(ID_Proyecto)
);